name: Triggers Data pipeline

on:
  push:
    branch: main
  # schedule:
  #   - cron: '26 18 * * *'

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Make our GCP Service Account secrets available for this run
      - name: Convert secrets to a file
        run: echo "$GCP_SERVICE_ACCOUNT" > clcg-dataengineering/bigquery-key.json
        shell: bash
        env:
          GCP_SERVICE_ACCOUNT: ${{secrets.GCP_SERVICE_ACCOUNT}}

      - name: Check secrets
        run: cat clcg-dataengineering/bigquery-key.json | jq -r '.client_id'
      # Using Mage
      # - name: Pull Mage Docker image
      #   run: docker pull mageai/mageai:0.9.9

      # - name: Execute Mage Pipeline
      #   run: docker run -v $(pwd)/clcg-dataengineering:/home/src mageai/mageai:0.9.9 /app/run_app.sh mage run /home/src github_actions

      # Using a main.py
      # - name: Pip install dependencies
      #   run: pip install -r requirements.txt --upgrade pip
      
      # - name: Run python file
      #   run: python main.py
